let val = Math.random()

console.log( Math.floor(val * 4))

// here the number generated is less than 4 (non negative numbers are included)

// generally the number generated by Math.randon() is a value between 0 to 1 (where 1 not included)